# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ViTables
email: vmas@vitables.org
description: > # this means to ignore newlines until "baseurl:"
  ViTables 3.0 is a GUI for browsing files in PyTables/HDF5 format. Enjoy with it navigating smoothly tables with hundreds of millions of rows.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vitables.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts_dir: ../_layouts
data_dir: ./_data
# collections: null

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Defaults for the front matter
defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
            author: "Vicent Mas"

# Handling Reading
safe:         false
include:      ["_pages", ".htaccess"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Sass load paths
sass:
    load_paths:
        - _saas
        - node_modules

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - yarn.lock

